services:
  postgres:
    image: postgres:15
    container_name: away_postgres
    restart: always
    environment:
      POSTGRES_USER: away_user
      POSTGRES_PASSWORD: away_pass
      POSTGRES_DB: away_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
